# Site settings
name: Tanmay Bansal
title: Tanmay Bansal
description: Rising senior at Cornell passionate about using data to drive strategy & social change.
url: https://tanmaybansal.com
baseurl: ''
email: tb444@cornell.edu
cover: https://bchiang7.github.io/img/og.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:tb444@cornell.edu
  - title: linkedin
    url: https://www.linkedin.com/in/tanmaybansal1

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
